name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.20.5'

    - name: Run unit tests
      run: go test -v ./...

    - name: Install dependencies
      run: .github/workflows/helpers/install-deps.sh

    - name: Build web
      run: ./web/app/make.sh all

    - name: Build linux binary
      run: .github/workflows/helpers/build-bin.sh build/ linux-amd64

    - name: Run integration tests
      run: .github/workflows/helpers/run-tests.sh build/notesium-linux-amd64

    - name: Print version
      run: build/notesium-linux-amd64 version --verbose

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

